plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
    id 'com.diffplug.spotless' version '7.0.2'
}

description = 'Compile-time Nexus bindings for Temporal workflow handlers'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withJavadocJar()
    withSourcesJar()
}

dependencies {
    api "io.temporal:temporal-sdk:${temporalVersion}"

    testImplementation "io.temporal:temporal-testing:${temporalVersion}"
    testImplementation 'junit:junit:4.13.2'

    testAnnotationProcessor files(sourceSets.main.output)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    if (JavaVersion.current().isJava9Compatible()) {
        options.release = 8
    }
}

tasks.withType(Test).configureEach {
    useJUnit()
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.addStringOption('Xdoclint:reference', '-quiet')
}

spotless {
    java {
        googleJavaFormat('1.24.0')
        target 'src/*/java/**/*.java'
        targetExclude '**/generated/**'
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            pom {
                name = 'Temporal Nexus Annotations'
                description = project.description
                url = 'https://github.com/quinnklassen/temporal-nexus-annotations'

                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }

                developers {
                    developer {
                        id = 'quinnklassen'
                        name = 'Quinn Klassen'
                    }
                }

                scm {
                    connection = 'scm:git:https://github.com/quinnklassen/temporal-nexus-annotations.git'
                    developerConnection = 'scm:git:ssh://git@github.com/quinnklassen/temporal-nexus-annotations.git'
                    url = 'https://github.com/quinnklassen/temporal-nexus-annotations'
                }
            }
        }
    }
}

if (providers.environmentVariable('SIGNING_KEY').isPresent()) {
    signing {
        useInMemoryPgpKeys(
                providers.environmentVariable('SIGNING_KEY').get(),
                providers.environmentVariable('SIGNING_PASSWORD').getOrElse(''))
        sign publishing.publications.mavenJava
    }
}
